name: 编译ZeroTierOne静态二进制文件
on:
  workflow_dispatch:
  schedule:
    - cron: "30 21 * * *"
jobs:
  build:
    name: 编译ZeroTierOne静态二进制文件
    runs-on: ubuntu-22.04
    steps:
      - name: 获取最新ZeroTierONE版本号
        run: echo "zerotier_tag_name=$(curl -sk "https://api.github.com/repos/zerotier/ZeroTierOne/releases/latest" | grep tag_name | cut -f4 -d '"')" >> $GITHUB_ENV
      - name: 编译ZeroTierOne静态二进制文件
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: curl -skL https://raw.githubusercontent.com/xilaochengv/Zerotier-One-Building-Script/main/Zerotier-One-Building-Script.sh -H "Authorization:token $TOKEN"
      - name: 上传文件到Releases
        uses: softprops/action-gh-release@v1
        with:
          files: zerotier-one-*
          tag_name: v${{ env.zerotier_tag_name }}
          body: "ZeroTier-One 静态编译文件"
